import Head from 'next/head'
import ContentDashboard from '../components/contentDashboard'

export default function Dashboard() {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ContentDashboard />
        </>
    )
}
