import Head from 'next/head'
import ContentLogs from '../components/contentLogs'

export default function Logs() {
    return (
        <>
            <Head>
                <title>Logs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ContentLogs />
        </>
    )
}
