import Head from 'next/head'

export default function Setting() {
    return (
        <>
            <Head>
                <title>Setting</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Setting</h1>
        </>
    )
}